---
- name: Generate list of packages to install
  ansible.builtin.set_fact:
    postgresql_packages: "{{ postgresql_server_packages + postgresql_extra_packages }}"

- name: Ensure PostgreSQL server packages are installed
  ansible.builtin.package:
    name: "{{ postgresql_packages }}"
    state: present
