---
- name: Defines PostgreSQL release version
  ansible.builtin.set_fact:
    postgresql_release: "{{ postgresql_version.split('.')[0] }}"

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Pre-installation system tasks
  ansible.builtin.import_tasks: system.yml

- name: OS-specific tasks
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Install PostgreSQL
  ansible.builtin.import_tasks: install.yml

- name: Configure PostgreSQL instance
  ansible.builtin.import_tasks: configure.yml

- name: Initialize PostgreSQL instance
  ansible.builtin.import_tasks: initialize.yml

- name: Manage PostgreSQL service
  ansible.builtin.import_tasks: service.yml

- name: Manage PostgreSQL instance tablespaces
  ansible.builtin.import_tasks: manage-tablespaces.yml

- name: Manage PostgreSQL instance databases
  ansible.builtin.import_tasks: manage-databases.yml

- name: Manage PostgreSQL instance roles
  ansible.builtin.import_tasks: manage-roles.yml

- name: Manage PostgreSQL instance extensions
  ansible.builtin.include_tasks: manage-extensions.yml
  with_items: "{{ postgresql_extensions }}"
  loop_control:
    loop_var: extension
