---
- name: Manage instance database(s) state
  community.postgresql.postgresql_db:
    name: "{{ db.name }}"
    owner: "{{ db.owner | default(omit) }}"
    encoding: "{{ db.encoding | default(omit) }}"
    lc_collate: "{{ db.lc_collate | default(omit) }}"
    lc_ctype: "{{ db.lc_ctype | default(omit) }}"
    template: "{{ db.template | default(omit) }}"
    conn_limit: "{{ db.conn_limit | default(omit) }}"
    tablespace: "{{ db.tablespace | default(omit) }}"
    state: "{{ db.state | default('present') }}"
  become: true
  become_user: postgres
  with_items: "{{ postgresql_databases }}"
  loop_control:
    loop_var: db
