---
- name: "Manage extension state - {{ extension.name }}"
  community.postgresql.postgresql_ext:
    name: "{{ extension.name }}"
    db: "{{ item }}"
    cascade: "{{ extension.cascade | default(false) }}"
    version: "{{ extension.version | default(omit) }}"
    state: "{{ extension.state }}"
  with_items: "{{ extension.databases | default(['postgres']) }}"
  loop_control:
    label: "{{ item }} -> {{ extension.state }}"
  become: true
  become_user: postgres
