---
- name: Ensure instance tablespaces directories are created
  ansible.builtin.file:
    path: "{{ tablespace.path }}"
    state: directory 
    owner: postgres
    group: postgres
    mode: '0700'
  with_items: "{{ postgresql_tablespaces }}"
  loop_control:
    loop_var: tablespace

- name: Manage instance tablespaces state
  community.postgresql.postgresql_tablespace:
    name: "{{ tablespace.name }}"
    path: "{{ tablespace.path }}"
    owner: "{{ tablespace.owner | default(omit) }}"
    set: "{{ tablespace.options | default(omit) }}"
    state: "{{ tablespace.state | default('present') }}"
  become: true
  become_user: postgres
  with_items: "{{ postgresql_tablespaces }}"
  loop_control:
    loop_var: tablespace
