---
- name: Ensure PostgreSQL service unit is applied
  ansible.builtin.template:
    src: postgresql.service.j2
    dest: /etc/systemd/system/postgresql.service
    owner: root
    group: root
    mode: '0644'

- name: Ensure PostgreSQL instance is enabled and started
  ansible.builtin.systemd:
    name: postgresql.service
    state: started
    enabled: true
    daemon_reload: true
