---
# - General -
postgresql_version: '14.8'

postgresql_restart_on_changes: true
postgresql_cluster_name: molecule-14

# - File locations -
postgresql_wal_dir: "{{ postgresql_root_dir }}/{{ postgresql_release }}/wal"

# - Repository and packages -
postgresql_packages:
  - "postgresql-{{ postgresql_release }}={{ postgresql_version }}-1.pgdg{{ ansible_distribution_version }}+1"
  - "postgresql-client-{{ postgresql_release }}={{ postgresql_version }}-1.pgdg{{ ansible_distribution_version }}+1"
  - "postgresql-{{ postgresql_release }}-cron"
  - "postgresql-{{ postgresql_release }}-repack"
  - "python3-psycopg2"
  - "libpq-dev"

# - Connection Settings -
postgresql_listen_addresses: "*"

# - Shared Library Preloading -
postgresql_shared_preload_libraries:
  - pg_stat_statements
  - pg_prewarm
  - pg_cron

# - Databases -
postgresql_databases:
  - name: moleculedb
    encoding: UTF-8
    lc_collate: C.UTF-8
    lc_ctype: C.UTF-8

# - Roles -
postgresql_roles:
  - name: molecule
    comment: "Molecule test user"
    password: molecule
    role_attr_flags: "LOGIN"
    conn_limit: 10
  - name: johndoe
    comment: "Molecule test user"
    password: johndoe
    role_attr_flags: "LOGIN"

postgresql_roles_privileges:
  - { type: database, roles: molecule, objects: moleculedb, privileges: 'ALL' }
  - { type: database, roles: johndoe,  objects: moleculedb, privileges: 'CONNECT' }

# - Extensions -
postgresql_extensions:
  - name: pg_stat_statements
    state: present
    databases: ['postgres', 'moleculedb']
  - name: pg_prewarm
    state: present
  - name: pg_buffercache
    state: present
  - name: pg_cron
    state: present

# - pg_hba entries - 
postgresql_hba_entries:
  - { type: local, db: 'all', user: 'all', method: 'scram-sha-256' }
  - { type: host,  db: 'all', user: 'all', address: '0.0.0.0/0', method: 'scram-sha-256' }

# - Extra configurations -
postgresql_extra_configurations:
  - 'pg_stat_statements.max = 10000'
  - 'pg_stat_statements.track = all'
  - 'pg_prewarm.autoprewarm = true'
  - 'pg_prewarm.autoprewarm_interval = 300s'
  - 'cron.use_background_workers = on'
