---
# - General -
postgresql_restart_on_changes: true
postgresql_cluster_name: molecule-default

# - File locations -
postgresql_wal_dir: "{{ postgresql_root_dir }}/{{ postgresql_release }}/wal"

# - Database initialization -
postgresql_initdb_checksum_enabled: true

# - Connection Settings -
postgresql_listen_addresses: "*"

# - Shared Library Preloading -
postgresql_shared_preload_libraries:
  - pg_stat_statements
  - pg_prewarm
  - pg_cron

# - Tablespaces -
postgresql_tablespaces:
  - name: tb1
    path: "{{ postgresql_root_dir }}/{{ postgresql_release }}/tb1"
    options:
      random_page_cost: '1.1'

# - Databases -
postgresql_databases:
  - name: moleculedb
    encoding: UTF-8
    lc_collate: C.UTF-8
    lc_ctype: C.UTF-8
    tablespace: tb1

# - Roles -
postgresql_roles:
  - name: molecule
    comment: "Molecule test user"
    password: molecule
    role_attr_flags: "LOGIN"
    conn_limit: 10
  - name: johndoe
    comment: "Molecule test user"
    password: johndoe
    role_attr_flags: "LOGIN"

postgresql_roles_privileges:
  - { type: database, roles: molecule, objects: moleculedb, privileges: 'ALL' }
  - { type: database, roles: johndoe,  objects: moleculedb, privileges: 'CONNECT' }

# - Extensions -
postgresql_extensions:
  - name: pg_stat_statements
    state: present
    databases: ['postgres', 'moleculedb']
  - name: pg_prewarm
    state: present
  - name: pg_buffercache
    state: present
  - name: pg_cron
    state: present

# - pg_hba entries - 
postgresql_hba_entries:
  - { type: local, db: 'all', user: 'all', method: 'scram-sha-256' }
  - { type: host,  db: 'all', user: 'all', address: '0.0.0.0/0', method: 'scram-sha-256' }

# - Extra configurations -
postgresql_extra_configurations:
  - 'pg_stat_statements.max = 10000'
  - 'pg_stat_statements.track = all'
  - 'pg_prewarm.autoprewarm = true'
  - 'pg_prewarm.autoprewarm_interval = 300s'
  - 'cron.use_background_workers = on'
